

spring:
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
    servlet:
      multipart:
          max-file-size: 100MB
          max-request-size: 100MB
server:
    port: 8080